x = """<div itemscope="itemscope" itemtype="https://schema.org/Product" class="product-card-block" style="border-color:#EBEBEB;" data-v-26279ff2 data-v-d4ced9e4><div class="badges product-card-block__badges-position" data-v-cffe8dba data-v-26279ff2><!----> <!----> <div class="badge-discount badge-discount_price-reduced" data-v-cffe8dba>
    ЦЕНА СНИЖЕНА
  </div> <div class="badge-loyal" data-v-cffe8dba><span class="ui-icon inline-block badge-loyal__icon ui-icon_bonuses" style="background-image:url(/_nuxt/img/bonuses.81b6a28.svg);width:28px;height:21px;" data-v-cffe8dba><!----></span> <div class="badge-loyal__amount" data-v-cffe8dba>от 3 бонусов</div></div></div> <button aria-label="добавить лекарство в избранное" type="button" class="favorite-button" data-v-26279ff2><span class="ui-icon inline-block ui-icon_heart" style="background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICAgIDxwYXRoIGQ9Ik0xNy43MjEgMi4wMDRjLTIuNDg1LjA3OC00LjM4NiAxLjIwNS01LjY0MSAzLjI5OGwtLjA4LjEzNy0uMDgtLjEzN0MxMC42MiAzLjEzMiA4LjYyMyAyIDYgMiAyLjgzMiAyIDAgNC40NzggMCA4LjVjMCA1LjIgNC42NDIgMTAuMjUxIDExLjQ4NiAxNC4zNTcuMzE2LjE5LjcxMi4xOSAxLjAyOCAwQzE5LjM1OCAxOC43NTEgMjQgMTMuNyAyNCA4LjUgMjQgNC40NzggMjEuMTY4IDIgMTggMmwtLjI3OS4wMDR6TTE4IDRjMi4xMTggMCA0IDEuNjQ3IDQgNC41bC0uMDA1LjI1MmMtLjE1MiAzLjk0NS0zLjg1MyA4LjE1LTkuNDE0IDExLjcxMWwtLjU4MS4zNjUtLjIxNi0uMTMzQzUuOTAxIDE3LjAwOSAyIDEyLjYwMyAyIDguNSAyIDUuNjQ3IDMuODgyIDQgNiA0YzIuNTM0IDAgNC4xNjMgMS4zNTcgNS4wNDIgNC4yODcuMjg1Ljk1IDEuNjMuOTUgMS45MTYgMEMxMy44MzcgNS4zNTcgMTUuNDY2IDQgMTggNHoiLz4KPC9zdmc+Cg==);width:24px;height:24px;"><!----></span></button> <div class="product-top" data-v-26279ff2><a href="/catalog/9858/" tabindex="-1" class="preview-img-wrapper" data-v-26279ff2><span data-v-26279ff2><img src="/resize/620x440/upload/iblock/10c/10cde18e5783740b4b63929e3a7b5412/acf0b36d54d763e8ab90cd602977ffe2.jpg" alt="ЛА-КРИ ГЕЛЬ ДЛЯ ТЕЛА 200 мл моющий" class="preload-image preview-img" data-v-26279ff2></span></a> <div class="product-card-block__info" data-v-26279ff2><!----> <!----> <a href="/catalog/9858/" class="product-card-block__title" data-v-26279ff2><span data-v-26279ff2>ЛА-КРИ ГЕЛЬ ДЛЯ ТЕЛА 200 мл моющий</span></a> <a href="/novosibirsk/catalog/materinstvo_i_detstvo/detskaya_gigiena/" aria-current="page" class="product-card-block__category nuxt-link-exact-active nuxt-link-active" data-v-26279ff2>
        Детская гигиена
      </a> <a href="/catalog/9858/#analogs" class="product-analogs-summary" data-v-26279ff2>
        15  аналогов от 96 ₽
      </a> <!----></div></div> <div class="product-card-block__bottom" data-v-26279ff2><!----> <div class="flex justify-between items-end w-full" data-v-26279ff2><div class="product-status" data-v-26279ff2><div class="product-status__item" data-v-26279ff2><span data-v-26279ff2>Сегодня <br data-v-26279ff2> <a href="/catalog/9858/#prices" class="product-drugstores-link" data-v-26279ff2>
              в 49 аптеках
            </a></span></div></div> <div itemprop="offers" itemscope="itemscope" itemtype="https://schema.org/Offer" class="product-price" data-v-26279ff2><div class="product-price__old-price" data-v-26279ff2>
          от 446 ₽
        </div> <div itemprop="price" class="product-price__current-price price-active price-green-product" data-v-26279ff2>
          от
          <span class="price-value" data-v-26279ff2> 356 ₽ </span></div> <!----></div></div> <button type="button" class="button button--red btn-buy-main button-big" data-v-a4e90ab2 data-v-26279ff2>В корзину</button></div></div>"""